### PR TITLE
Add async logger

### PR DESCRIPTION
**Pull request by mstn**
I added a simple `LoggerTask` based on `LoggerIO` implementation. Why?

* External logging services are asynchronous
* In [some](https://levelup.gitconnected.com/avoiding-the-pitfalls-of-async-node-js-functions-in-aws-lambda-941220582e7a) contexts, we cannot just "throw away" a promise: we need to "wait" explicitly.

Thanks!

### CODE REVIEW

**Review by gcanti — CHANGES_REQUESTED** [review]
Thanks @mstn, travis is failing because there are no tests. 

Also some required comments are missing: in order to generate the docs you have to add the `@since` tag to all APIs. 

Example:

```ts
/**
 * @since 0.3.1
 */
export const URI = 'LoggerTask'
```

You can check the `IO.ts` module to get an idea.

**Comment by mstn** [comment]
Sorry, I missed tests. I'll do it!

**Comment by mstn** [comment]
@gcanti the version should be `0.4.0` imo, it is not a bug fix, but a new feature, correct?

**Comment by gcanti** [comment]
@mstn no, before v1.0.0 bumping the minor means a breaking change

**Review by gcanti — APPROVED** [review]

**Comment by gcanti** [comment]
Thanks @mstn, released.

**Pull request merged**
